In [1]:
import os

In [2]:
%pwd

'/Users/marioholmes/Sales/research/data'

In [5]:
os.chdir("..//")

In [6]:
%pwd

'/Users/marioholmes/Sales'

# **DATA VALIDATION**

In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("artifacts/data_ingestion/retail_data.csv")
df

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,...,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
0,8691788.0,37249.0,Michelle Harrington,Ebony39@gmail.com,1.414787e+09,3959 Amanda Burgs,Dortmund,Berlin,77985.0,Germany,...,324.086270,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.0,Cycling shorts
1,2174773.0,69749.0,Kelsey Hill,Mark36@gmail.com,6.852900e+09,82072 Dawn Centers,Nottingham,England,99071.0,UK,...,806.707815,Electronics,Samsung,Tablet,Excellent,Standard,Credit Card,Processing,4.0,Lenovo Tab
2,6679610.0,30192.0,Scott Jensen,Shane85@gmail.com,8.362160e+09,4133 Young Canyon,Geelong,New South Wales,75929.0,Australia,...,1063.432799,Books,Penguin Books,Children's,Average,Same-Day,Credit Card,Processing,2.0,Sports equipment
3,7232460.0,62101.0,Joseph Miller,Mary34@gmail.com,2.776752e+09,8148 Thomas Creek Suite 100,Edmonton,Ontario,88420.0,Canada,...,2466.854021,Home Decor,Home Depot,Tools,Excellent,Standard,PayPal,Processing,4.0,Utility knife
4,4983775.0,27901.0,Debra Coleman,Charles30@gmail.com,9.098268e+09,5813 Lori Ports Suite 269,Bristol,England,48704.0,UK,...,248.553049,Grocery,Nestle,Chocolate,Bad,Standard,Cash,Shipped,1.0,Chocolate cookies
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302005,4246475.0,12104.0,Meagan Ellis,Courtney60@gmail.com,7.466354e+09,389 Todd Path Apt. 159,Townsville,New South Wales,4567.0,Australia,...,973.962984,Books,Penguin Books,Fiction,Bad,Same-Day,Cash,Processing,1.0,Historical fiction
302006,1197603.0,69772.0,Mathew Beck,Jennifer71@gmail.com,5.754305e+09,52809 Mark Forges,Hanover,Berlin,16852.0,Germany,...,285.137301,Electronics,Apple,Laptop,Excellent,Same-Day,Cash,Processing,5.0,LG Gram
302007,7743242.0,28449.0,Daniel Lee,Christopher100@gmail.com,9.382530e+09,407 Aaron Crossing Suite 495,Brighton,England,88038.0,UK,...,182.105285,Clothing,Adidas,Jacket,Average,Express,Cash,Shipped,2.0,Parka
302008,9301950.0,45477.0,Patrick Wilson,Rebecca65@gmail.com,9.373222e+09,3204 Baird Port,Halifax,Ontario,67608.0,Canada,...,120.834784,Home Decor,IKEA,Furniture,Good,Standard,Cash,Shipped,4.0,TV stand
302009,2882826.0,53626.0,Dustin Merritt,William14@gmail.com,9.518927e+09,143 Amanda Crescent,Tucson,West Virginia,25242.0,USA,...,2382.233417,Home Decor,Home Depot,Decorations,Average,Same-Day,Cash,Shipped,2.0,Clocks

In [10]:
# Dataset information
print(f"\033[1mInformation summary of dataset before cleaning\033[0m \n")
df.info()
print("-" * 100)

# Missing values analysis
missing_percentages = round(df.isnull().sum() / len(df) * 100, 2)
print(
    f"\033[1mPercentage of missing values within dataset before cleaning\033[0m \n{missing_percentages}"
)
print("-" * 100)

# Unique values analysis
unique_percentages = round(df.nunique() / len(df) * 100, 2)
print(
    f"\033[1mPercentage of unique values within dataset before cleaning\033[0m \n{unique_percentages}"
)
print("-" * 100)

# Numerical columns statistics
print(
    f"\033[1mTranspose of metrics of numerical columns in dataset before cleaning\033[0m \n{df.describe().T}"
)
print("-" * 100)

# Duplicate rows check
duplicate_percentage = round((df.duplicated().sum() / len(df)) * 100, 2)
print(f"\033[1mPercentage of duplicate rows:\033[0m {duplicate_percentage}%")
print("-" * 100)

# Zero values check for numerical columns
numerical_columns = df.select_dtypes(include=["int64", "float64"]).columns
zero_percentages = round((df[numerical_columns] == 0).sum() / len(df) * 100, 2)
print(
    f"\033[1mPercentage of zero values in numerical columns:\033[0m \n{zero_percentages}"
)
print("-" * 100)

# Data-type distribution
dtype_counts = df.dtypes.value_counts()
print(f"\033[1mDistribution of data types in the dataset:\033[0m \n{dtype_counts}")
print("-" * 100)

# Duplicate values analysis for each column
duplicate_percentages = {}
for column in df.columns:
    duplicate_percentages[column] = round(
        (df[column].duplicated().sum() / len(df)) * 100, 2
    )

print("\033[1mPercentage of duplicate values in each column:\033[0m")
for column, percentage in duplicate_percentages.items():
    print(f"{column}: {percentage}%")

Information summary of dataset before cleaning

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302010 entries, 0 to 302009
Data columns (total 30 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction_ID    301677 non-null  float64
 1   Customer_ID       301702 non-null  float64
 2   Name              301628 non-null  object
 3   Email             301663 non-null  object
 4   Phone             301648 non-null  float64
 5   Address           301695 non-null  object
 6   City              301762 non-null  object
 7   State             301729 non-null  object
 8   Zipcode           301670 non-null  float64
 9   Country           301739 non-null  object
 10  Age               301837 non-null  float64
 11  Gender            301693 non-null  object
 12  Income            301720 non-null  object
 13  Customer_Segment  301795 non-null  object
 14  Date              301651 non-null  object
 15  Year              301660 non-null  float64
 16  Month             301737 non-null  object
 17  Time              301660 non-null  object
 18  Total_Purchases   301649 non-null  float64
 19  Amount            301653 non-null  float64
 20  Total_Amount      301660 non-null  float64
 21  Product_Category  301727 non-null  object
 22  Product_Brand     301729 non-null  object
 23  Product_Type      302010 non-null  object
 24  Feedback          301826 non-null  object
 25  Shipping_Method   301673 non-null  object
 26  Payment_Method    301713 non-null  object
 27  Order_Status      301775 non-null  object
 28  Ratings           301826 non-null  float64
 29  products          302010 non-null  object
dtypes: float64(10), object(20)
memory usage: 69.1+ MB
----------------------------------------------------------------------------------------------------
Percentage of missing values within dataset before cleaning
Transaction_ID      0.11
Customer_ID         0.10
Name                0.13
Email               0.11
Phone               0.12
Address             0.10
City                0.08
State               0.09
Zipcode             0.11
Country             0.09
Age                 0.06
Gender              0.10
Income              0.10
Customer_Segment    0.07
Date                0.12
Year                0.12
Month               0.09
Time                0.12
Total_Purchases     0.12
Amount              0.12
Total_Amount        0.12
Product_Category    0.09
Product_Brand       0.09
Product_Type        0.00
Feedback            0.06
Shipping_Method     0.11
Payment_Method      0.10
Order_Status        0.08
Ratings             0.06
products            0.00
dtype: float64
----------------------------------------------------------------------------------------------------
Percentage of unique values within dataset before cleaning
Transaction_ID      97.50
Customer_ID         28.73
Name                52.78
Email               17.51
Phone               99.10
Address             99.11
City                 0.04
State                0.02
Zipcode             31.12
Country              0.00
Age                  0.02
Gender               0.00
Income               0.00
Customer_Segment     0.00
Date                 0.12
Year                 0.00
Month                0.00
Time                27.71
Total_Purchases      0.00
Amount              99.10
Total_Amount        99.10
Product_Category     0.00
Product_Brand        0.01
Product_Type         0.01
Feedback             0.00
Shipping_Method      0.00
Payment_Method       0.00
Order_Status         0.00
Ratings              0.00
products             0.11
dtype: float64
----------------------------------------------------------------------------------------------------
Transpose of metrics of numerical columns in dataset before cleaning
                    count          mean           std           min  \
Transaction_ID   301677.0  5.495823e+06  2.595565e+06  1.000007e+06
Customer_ID      301702.0  5.500655e+04  2.600568e+04  1.000000e+04
Phone            301648.0  5.501464e+09  2.596017e+09  1.000049e+09
Zipcode          301670.0  5.029895e+04  2.897281e+04  5.010000e+02
Age              301837.0  3.548133e+01  1.502193e+01  1.800000e+01
Year             301660.0  2.023165e+03  3.712832e-01  2.023000e+03
Total_Purchases  301649.0  5.359729e+00  2.868575e+00  1.000000e+00
Amount           301653.0  2.551637e+02  1.413896e+02  1.000022e+01
Total_Amount     301660.0  1.367651e+03  1.128999e+03  1.000375e+01
Ratings          301826.0  3.162670e+00  1.320827e+00  1.000000e+00

                          25%           50%           75%           max
Transaction_ID   3.247930e+06  5.499657e+06  7.739509e+06  9.999995e+06
Customer_ID      3.246925e+04  5.501200e+04  7.751100e+04  9.999900e+04
Phone            3.255061e+09  5.505812e+09  7.749860e+09  9.999996e+09
Zipcode          2.542500e+04  5.060250e+04  7.525200e+04  9.994900e+04
Age              2.200000e+01  3.200000e+01  4.600000e+01  7.000000e+01
Year             2.023000e+03  2.023000e+03  2.023000e+03  2.024000e+03
Total_Purchases  3.000000e+00  5.000000e+00  8.000000e+00  1.000000e+01
Amount           1.328908e+02  2.554710e+02  3.776726e+02  4.999979e+02
Total_Amount     4.387243e+02  1.041118e+03  2.030000e+03  4.999626e+03
Ratings          2.000000e+00  3.000000e+00  4.000000e+00  5.000000e+00
----------------------------------------------------------------------------------------------------
Percentage of duplicate rows: 0.0%
----------------------------------------------------------------------------------------------------
Percentage of zero values in numerical columns:
Transaction_ID     0.0
Customer_ID        0.0
Phone              0.0
Zipcode            0.0
Age                0.0
Year               0.0
Total_Purchases    0.0
Amount             0.0
Total_Amount       0.0
Ratings            0.0
dtype: float64
----------------------------------------------------------------------------------------------------
Distribution of data types in the dataset:
object     20
float64    10
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
Percentage of duplicate values in each column:
Transaction_ID: 2.5%
Customer_ID: 71.27%
Name: 47.22%
Email: 82.48%
Phone: 0.9%
Address: 0.89%
City: 99.96%
State: 99.98%
Zipcode: 68.88%
Country: 100.0%
Age: 99.98%
Gender: 100.0%
Income: 100.0%
Customer_Segment: 100.0%
Date: 99.88%
Year: 100.0%
Month: 100.0%
Time: 72.29%
Total_Purchases: 100.0%
Amount: 0.9%
Total_Amount: 0.9%
Product_Category: 100.0%
Product_Brand: 99.99%
Product_Type: 99.99%
Feedback: 100.0%
Shipping_Method: 100.0%
Payment_Method: 100.0%
Order_Status: 100.0%
Ratings: 100.0%
products: 99.89%

In [11]:
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class DataValidationConfig:
    root_dir: Path
    STATUS_FILE: str
    unzip_data_dir: Path
    all_schema: dict

In [12]:
from src.Ecommerce.constants import *
from src.Ecommerce.utils.common import read_yaml, create_directories

In [13]:
class ConfigurationManager:
    def __init__(
        self,
        config_filepath=CONFIG_FILE_PATH,
        params_filepath=PARAMS_FILE_PATH,
        schema_filepath=SCHEMA_FILE_PATH,
    ):
        self.config = read_yaml(config_filepath)
        self.params = read_yaml(params_filepath)
        self.schema = read_yaml(schema_filepath)

        create_directories([self.config.artifacts_root])

    def get_data_validation_config(self) -> DataValidationConfig:
        config = self.config.data_validation
        schema = self.schema.COLUMNS

        create_directories([config.root_dir])

        data_validation_config = DataValidationConfig(
            root_dir=config.root_dir,
            STATUS_FILE=config.STATUS_FILE,
            unzip_data_dir=config.unzip_data_dir,
            all_schema=schema,
        )

        return data_validation_config

In [14]:
import os
from src.Ecommerce import logger

In [17]:
class DataValidation:
    def __init__(self, config: DataValidationConfig):
        self.config = config

    def validate_all_columns(self) -> bool:
        try:
            validation_status = None

            data = pd.read_csv(self.config.unzip_data_dir)
            all_cols = list(data.columns)

            all_schema = self.config.all_schema.keys()

            for col in all_cols:
                if col not in all_schema:
                    validation_status = False
                    with open(self.config.STATUS_FILE, "w") as f:
                        f.write(f"Validation status: {validation_status}")
                else:
                    validation_status = True
                    with open(self.config.STATUS_FILE, "w") as f:
                        f.write(f"Validation status: {validation_status}")

            return validation_status

        except Exception as e:
            raise e

In [20]:
try:
    config = ConfigurationManager()
    data_validation_config = config.get_data_validation_config()
    data_validation = DataValidation(config=data_validation_config)
    data_validation.validate_all_columns()
except Exception as e:
    raise e

[2024-12-31 10:57:55,906]: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-12-31 10:57:55,908]: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-31 10:57:55,910]: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-12-31 10:57:55,911]: INFO: common: created directory at: artifacts]
[2024-12-31 10:57:55,912]: INFO: common: created directory at: artifacts/data_validation]

In [ ]:
# Get the schema columns and actual columns
schema_columns = data_validation_config.all_schema.keys()
actual_columns = df.columns

print("Schema columns:", list(schema_columns))
print("\nActual columns:", list(actual_columns))

# Find columns that are in the data but not in schema
extra_columns = set(actual_columns) - set(schema_columns)
# Find columns that are in schema but not in data
missing_columns = set(schema_columns) - set(actual_columns)

print("\nColumns in data but not in schema:", list(extra_columns))
print("Columns in schema but not in data:", list(missing_columns))